# Generated by Django 4.1.7 on 2023-03-24 05:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='equipment/photo', verbose_name='Фото оборудования')),
                ('title', models.CharField(max_length=255, verbose_name='Название оборудования')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кол-во')),
                ('price', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена за смену')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone_number', models.CharField(max_length=23, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=255, verbose_name='Почта')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
