# Generated by Django 4.1.7 on 2023-03-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_equipment_created_time_equipment_update_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название категории')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='description',
            field=models.TextField(default=2, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
