# Generated by Django 4.1.7 on 2023-03-27 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_categoryequipment_equipment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.categoryequipment', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
