# Generated by Django 4.1.7 on 2023-03-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_equipment_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryequipment',
            options={'verbose_name': 'Категории', 'verbose_name_plural': 'Категория'},
        ),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.CharField(max_length=95, verbose_name='Описание'),
        ),
    ]
