# Generated by Django 4.1.7 on 2023-03-27 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_categoryequipment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='equipment/photo', verbose_name='Фото оборудования')),
                ('title', models.CharField(max_length=255, verbose_name='Название оборудования')),
                ('description', models.CharField(max_length=95, verbose_name='Описание')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кол-во')),
                ('price', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена за смену')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
            ],
            options={
                'verbose_name': 'Звуковое оборудование',
                'verbose_name_plural': 'Звуковое оборудование',
            },
        ),
        migrations.CreateModel(
            name='Coder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='category',
        ),
        migrations.DeleteModel(
            name='CategoryEquipment',
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
    ]
