# Generated by Django 4.1.7 on 2023-03-27 11:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_camera_coder_light_music_remove_equipment_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='equipment/photo', verbose_name='Фото оборудования')),
                ('title', models.CharField(max_length=255, verbose_name='Название оборудования')),
                ('description', models.CharField(max_length=95, verbose_name='Описание')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кол-во')),
                ('price', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена за смену')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
            },
        ),
        migrations.DeleteModel(
            name='Camera',
        ),
        migrations.DeleteModel(
            name='Coder',
        ),
        migrations.DeleteModel(
            name='Light',
        ),
        migrations.DeleteModel(
            name='Music',
        ),
    ]
