# Generated by Django 4.1.7 on 2023-03-28 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_category_options_alter_equipment_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='photo',
            field=models.FileField(upload_to='equipment/photo', validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'svg'])], verbose_name='Фото оборудования'),
        ),
    ]
